/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consola;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jpalazzesi
 */
public class NuevaPc extends javax.swing.JFrame {
    public int id;
    /**
     * Creates new form NuevaPc
     */
    public NuevaPc() {
        initComponents();
    }
    public NuevaPc(int idpc){
        initComponents();
        this.id = idpc;
        ConexionSegura con = new ConexionSegura();
        try{
            con.setPs("select * from inventariopc where id=?");
            con.ps.setInt(1, id);
            ResultSet r = con.ps.executeQuery();
            r.next();
            txtIp.setText(r.getString("ip"));
            txtNombreEquipo.setText(r.getString("nombrentbios"));
            txtUsuario.setText(r.getString("usuario"));
            txtSector.setText(r.getString("sector"));
            txtInventario.setText(r.getString("numeroinventario"));
            txtMother.setText(r.getString("mother"));
            txtMicro.setText(r.getString("micro"));
            txtMemoria.setText(r.getString("memoria"));
            btnGuardar.setText("Actualizar");
            this.setTitle("Actualizar");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al obtener el equipo");
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtNombreEquipo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtSector = new javax.swing.JTextField();
        txtInventario = new javax.swing.JTextField();
        txtMother = new javax.swing.JTextField();
        txtMicro = new javax.swing.JTextField();
        txtMemoria = new javax.swing.JTextField();
        cboTipoMemoria = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Equipo"));

        jLabel1.setText("Direccion IP");

        jLabel2.setText("Nombre Equipo");

        jLabel3.setText("Usuario");

        jLabel4.setText("Sector");

        jLabel5.setText("Número Inventario");

        jLabel6.setText("Mother");

        jLabel7.setText("Micro");

        jLabel8.setText("Memoria");

        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });

        txtMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotherActionPerformed(evt);
            }
        });

        txtMicro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMicroActionPerformed(evt);
            }
        });

        cboTipoMemoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GB", "MB", "KB" }));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turnos/iconos/disk.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turnos/iconos/cross.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setDisplayedMnemonicIndex(1);
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtMicro)
                    .addComponent(txtMother)
                    .addComponent(txtInventario)
                    .addComponent(txtSector)
                    .addComponent(txtUsuario)
                    .addComponent(txtNombreEquipo)
                    .addComponent(txtIp)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMicro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(txtMemoria)
                    .addComponent(cboTipoMemoria))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    private void txtMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotherActionPerformed

    private void txtMicroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMicroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(id == 0){
            if(txtIp.getText() !=null){
                ConexionSegura con = new ConexionSegura();
                try{
                    con.setPs("insert into inventariopc(ip, nombrentbios, usuario, sector, numeroinventario, mother, micro, memoria, unidadmemoria) "
                        + "values(?, ?, ?, ?, ?, ?, ?, ?, ?)");
                    con.ps.setString(1, txtIp.getText().toString());
                    con.ps.setString(2, txtNombreEquipo.getText().toString());
                    con.ps.setString(3, txtUsuario.getText().toString());
                    con.ps.setString(4, txtSector.getText().toString());
                    con.ps.setString(5, txtInventario.getText().toString());
                    con.ps.setString(6, txtMother.getText().toString());
                    con.ps.setString(7, txtMicro.getText().toString());
                    con.ps.setString(8, txtMemoria.getText().toString());
                    con.ps.setString(9, cboTipoMemoria.getSelectedItem().toString());
                    con.ps.executeUpdate();
                }catch(Exception e){
                    System.out.println(e);
                }
                this.dispose();
                new tablasCombos().getInventarioPC("", ListadoPcs.jtblListadoPC);
            }else{
                JOptionPane.showMessageDialog(null, "Dirección IP es campo Obligatorio");
            }
        }else{
            if(txtIp.getText() !=null){
                ConexionSegura con = new ConexionSegura();
                try{
                    con.setPs("update inventariopc set ip = ?, nombrentbios = ?, usuario = ?, sector = ?, numeroinventario = ?, mother = ?, micro = ?, memoria = ?, unidadmemoria = ? where id=?");
                    con.ps.setString(1, txtIp.getText().toString());
                    con.ps.setString(2, txtNombreEquipo.getText().toString());
                    con.ps.setString(3, txtUsuario.getText().toString());
                    con.ps.setString(4, txtSector.getText().toString());
                    con.ps.setString(5, txtInventario.getText().toString());
                    con.ps.setString(6, txtMother.getText().toString());
                    con.ps.setString(7, txtMicro.getText().toString());
                    con.ps.setString(8, txtMemoria.getText().toString());
                    con.ps.setString(9, cboTipoMemoria.getSelectedItem().toString());
                    con.ps.setInt(10, id);
                    con.ps.executeUpdate();
                }catch(Exception e){
                    System.out.println(e);
                }
                JOptionPane.showMessageDialog(null, "Actualizado Correctamente!");
                this.dispose();
                new tablasCombos().getInventarioPC("", ListadoPcs.jtblListadoPC);
            }else{
                JOptionPane.showMessageDialog(null, "Dirección IP es campo Obligatorio");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboTipoMemoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInventario;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtMicro;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
